require("user.utils.autoCmd.transparent")
require("user.utils.autoCmd.attachColor")
require("user.utils.autoCmd.fileType")
require("user.utils.autoCmd.saveAndFormat")
require("user.utils.autoCmd.autoRun")
-- require("user.utils.autoCmd.whichKey")
