-- local bufnr = vim.api.nvim_get_current_buf()

-- local group = vim.api.nvim_create_augroup("SaveNFormat", { clear = true })
vim.api.nvim_create_user_command("SaveNFormat", function()
	-- vim.cmd("lua 	require('user.utils.format').format()")
	-- vim.cmd("lua vim.lsp.buf.format()")
	-- vim.cmd("LspZeroFormat")
	-- vim.cmd(lsp_formatting(bufnr))
	vim.cmd("w!")
end, {})
