return {
  kindIcon = function(self)
    return {
      [1] = { 'File', ' ', self.colors.fg },
      [2] = { 'Module', ' ', self.colors.blue },
      [3] = { 'Namespace', ' ', self.colors.orange },
      [4] = { 'Package', ' ', self.colors.violet },
      [5] = { 'Class', ' ', self.colors.violet },
      [6] = { 'Method', ' ', self.colors.violet },
      [7] = { 'Property', ' ', self.colors.cyan },
      [8] = { 'Field', ' ', self.colors.teal },
      [9] = { 'Constructor', ' ', self.colors.blue },
      [10] = { 'Enum', '了', self.colors.green },
      [11] = { 'Interface', ' ', self.colors.orange },
      [12] = { 'Function', ' ', self.colors.violet },
      [13] = { 'Variable', ' ', self.colors.blue },
      [14] = { 'Constant', ' ', self.colors.cyan },
      [15] = { 'String', ' ', self.colors.green },
      [16] = { 'Number', ' ', self.colors.green },
      [17] = { 'Boolean', ' ', self.colors.orange },
      [18] = { 'Array', ' ', self.colors.blue },
      [19] = { 'Object', ' ', self.colors.orange },
      [20] = { 'Key', ' ', self.colors.red },
      [21] = { 'Null', ' ', self.colors.red },
      [22] = { 'EnumMember', ' ', self.colors.green },
      [23] = { 'Struct', ' ', self.colors.violet },
      [24] = { 'Event', ' ', self.colors.violet },
      [25] = { 'Operator', ' ', self.colors.green },
      [26] = { 'TypeParameter', ' ', self.colors.green },
      -- ccls
      [252] = { 'TypeAlias', ' ', self.colors.green },
      [253] = { 'Parameter', ' ', self.colors.blue },
      [254] = { 'StaticMethod', 'ﴂ ', self.colors.orange },
      [255] = { 'Macro', ' ', self.colors.red },
    }
  end,
  kind_icons = {
    ['cmp-tw2css'] = '',
    Copilot = ' ',
    Class = ' ',
    Color = ' ',
    Constant = 'ﲀ ',
    Constructor = ' ',
    Enum = '練',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = '',
    Folder = ' ',
    Function = ' ',
    Interface = 'ﰮ ',
    Keyword = ' ',
    Method = ' ',
    Module = ' ',
    Operator = '',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    Struct = ' ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = '塞',
    Value = ' ',
    Variable = ' ',
  },
}
