require("user.treesitter.ts")
require("user.treesitter.tsContext")
require("user.treesitter.tsIndent")
require("user.treesitter.comment")
require("user.treesitter.autoTag")
require("user.treesitter.autoPair").setup()
