-- coding
require("user.swissKnife.coding.gitsigns")
require("user.swissKnife.coding.gitConflict")
require("user.swissKnife.coding.refactoring")
require("user.swissKnife.coding.sniprun")
require("user.swissKnife.coding.codi")
require("user.swissKnife.coding.toggleterm").setup()

-- tool
require("user.swissKnife.mini")
require("user.swissKnife.spectre")
require("user.swissKnife.numb")
require("user.swissKnife.colorizer")
require("user.swissKnife.colortils")
require("user.swissKnife.zen")
require("user.swissKnife.harpoon")
require("user.swissKnife.smoothScroll")
require("user.swissKnife.sessionManager")
require("user.swissKnife.betterEscape")
require("user.swissKnife.indentOmatic")
