name: Main
on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          files: .
          annotate: warning

  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check .
